name: Test Code Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 리포지토리를 가져오기
        uses: actions/checkout@v3

      - name: JDK17을 설치
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup MySQL
        uses: samin/mysql-action@v1
        with:
          mysql database: 'bankdb'
          mysql user: 'jihwan'
          mysql password: 'hwani'

      - name: Gradle 명령 실행을 위한 권한 부여
        run: chmod +x gradlew

      - name: Gradle test를 실행 후 report 추출
        run: ./gradlew build jacocoTestReport

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./build/reports/jacoco/test/jacocoTestReport.xml
